apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-audit-logger
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 192Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:MaxRAMPercentage=35.0 -XX:ActiveProcessorCount=4
