apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-audit-logger
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{image}}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 80m
      memory: 128Mi
  secureLogs:
    enabled: true
  kafka:
    pool: {{kafka_pool}}
